# Generated by Django 4.1.3 on 2023-09-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
