# Generated by Django 4.1.3 on 2023-10-02 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipieapp', '0003_remove_recipe_last_name_lastrecipename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='rawmaterials',
        ),
        migrations.AddField(
            model_name='reciperawmaterials',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipieapp.recipe'),
        ),
    ]
