# Generated by Django 4.1.3 on 2023-10-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipieapp', '0004_remove_recipe_rawmaterials_reciperawmaterials_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperawmaterials',
            name='quantity_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
