# Generated by Django 4.1.3 on 2023-10-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipieapp', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phonenumber',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
